import type { Metadata } from "next";
import { Epilogue, Inter, Poppins } from "next/font/google";
import { UserProvider } from "@/contexts/UserContext";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["900"] });
const epilogue = Epilogue({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <SessionProvider>{children}</SessionProvider>
        </UserProvider>
      </body>
    </html>
  );
}
